camera:
  resolution: (1920, 1080)
  background_color: "#000000"
text:
  font: "Mongolian Baiti"
  alignment: "LEFT"
directories:
  mirror_module_path: True
  removed_mirror_prefix: "D:/zhixin_videos"
  base: "C:/Users/zhixin/OneDrive/Zhixin/"
  subdirs:
    raster_images: "images/raster"
    vector_images: "images/vector"
    downloads: "manim_downloads"
  cache: "cache"
tex:
  template: "ctex"
universal_import_line: "from manim_imports_custom import *"